title: Quick Start for the UV-K5
description: Just the basics to get you up and running with the most useful settings on your new HT.
theme: just-the-docs

url: https://gilntk.github.io/uvk5qsg
baseurl: 
repository: just-the-docs/just-the-docs # for github-metadata

permalink: pretty

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
